/**
 * The Features catalogue: atomic inventory of every capability in the
 * app, with a precise "shipped / partial / planned / deprecated" status.
 *
 * This is the single source of truth for "is X built or not?". When a
 * teammate (or AI agent) is about to start work, they should grep this
 * file FIRST. If the feature shows as "shipped" with codeRefs, don't
 * rebuild it.
 */
import type { Feature } from "../types";

export const FEATURES: Feature[] = [
  /* ─────────── Auth ─────────── */
  {
    slug: "phone-otp-signup",
    title: "Phone OTP signup + login",
    summary: "Sign up and sign in with a phone number; OTP delivered via MSG91. Idempotent: re-using the same phone returns the existing account.",
    area: "Auth",
    status: "shipped",
    shipped_at: "2026-05-26",
    codeRefs: ["src/pages/Login.tsx", "supabase/functions/send-otp/index.ts", "supabase/functions/verify-otp/index.ts"],
    appRefs: ["/login"],
    details: "MSG91 template-based delivery, rate-limited via `phone_otp_attempts` table (5 attempts per 15 min). On verify, the user row is upserted by phone, and any matching legacy_enrolments are auto-granted.",
  },
  {
    slug: "google-oauth",
    title: "Google OAuth (planned)",
    summary: "Optional social sign-in to reduce friction for desktop users. Not yet implemented; Supabase Auth supports it but the UI hookup is pending.",
    area: "Auth",
    status: "planned",
  },
  {
    slug: "account-deletion",
    title: "Account deletion (right-to-erasure)",
    summary: "Users can delete their account from /profile → settings. Edge function handles cascade cleanup of enrolments, posts, submissions, and removes the auth row.",
    area: "Auth",
    status: "shipped",
    codeRefs: ["supabase/functions/delete-account/index.ts", "supabase/migrations/20260522180000_account_deletion.sql"],
    appRefs: ["/profile"],
  },
  {
    slug: "role-system",
    title: "Role-based access (owner/admin/instructor/author/support/student)",
    summary: "Five admin roles + student. Each gets a different slice of /admin via canAccessRoute. Owner is the CEO tier, never demotable.",
    area: "Auth",
    status: "shipped",
    codeRefs: ["src/lib/permissions.ts", "supabase/migrations/20260523120000_add_owner_role.sql"],
  },

  /* ─────────── Storefront ─────────── */
  {
    slug: "browse-page",
    title: "Browse page (public offering catalogue)",
    summary: "Filtered, searchable grid of all public offerings. Categorized by product_tier (Masterclass, Live Cohort, Workshop, Resources). Mobbin-grounded UX.",
    area: "Storefront",
    status: "shipped",
    codeRefs: ["src/pages/BrowsePage.tsx"],
    appRefs: ["/browse"],
  },
  {
    slug: "public-offering",
    title: "Public offering page (sales page)",
    summary: "Per-offering sales page: hero video, what-you'll-learn rail, curriculum module list, instructor bio, FAQs, reviews, social proof. Buy or preview free chapter.",
    area: "Storefront",
    status: "shipped",
    codeRefs: ["src/pages/PublicOffering.tsx"],
    appRefs: ["/offering/:slug"],
  },
  {
    slug: "free-preview-chapter",
    title: "Free preview chapter (anon play)",
    summary: "Any chapter marked is_free can be played by anonymous visitors. VdoCipher serves a watermarked-but-DRM-protected stream.",
    area: "Storefront",
    status: "shipped",
    codeRefs: ["supabase/migrations/2026...allow_anon_vdocipher_views.sql", "src/pages/ChapterViewer.tsx"],
  },

  /* ─────────── Checkout ─────────── */
  {
    slug: "razorpay-checkout",
    title: "Razorpay checkout (prod + test)",
    summary: "Razorpay Standard Checkout integration. Server creates an order, client opens Razorpay modal, webhook captures the payment and creates the enrolment.",
    area: "Checkout",
    status: "shipped",
    codeRefs: ["supabase/functions/create-razorpay-order/index.ts", "supabase/functions/razorpay-webhook/index.ts", "src/pages/CheckoutPage.tsx"],
  },
  {
    slug: "guest-checkout",
    title: "Guest checkout",
    summary: "Ad traffic can buy without signing up first. Account is created after the payment captures, using the email/phone they entered.",
    area: "Checkout",
    status: "shipped",
    codeRefs: ["supabase/functions/guest-create-order/index.ts"],
  },
  {
    slug: "coupons",
    title: "Coupon codes",
    summary: "Admin-issued discount codes (percentage or flat). Tracks usage, max_uses, valid_until. Surfaced in /admin/coupons.",
    area: "Checkout",
    status: "shipped",
    codeRefs: ["src/pages/admin/AdminCoupons.tsx"],
    appRefs: ["/admin/coupons"],
  },
  {
    slug: "refunds",
    title: "Refunds",
    summary: "Admin can issue full or partial refunds from /admin/revenue. process-refund edge function calls Razorpay's refund API and updates the order status.",
    area: "Checkout",
    status: "shipped",
    codeRefs: ["supabase/functions/process-refund/index.ts"],
    appRefs: ["/admin/revenue"],
  },
  {
    slug: "duplicate-purchase-guard",
    title: "Duplicate-purchase guard",
    summary: "Cannot accidentally buy the same offering twice. The order-creation step checks for an active enrolment and short-circuits.",
    area: "Checkout",
    status: "shipped",
  },

  /* ─────────── Learning ─────────── */
  {
    slug: "chapter-viewer",
    title: "Chapter viewer (VdoCipher + HLS fallback)",
    summary: "DRM-protected video playback with chapter sidebar, Up Next, progress tracking, cross-device notes, Q&A thread.",
    area: "Learning",
    status: "shipped",
    codeRefs: ["src/pages/ChapterViewer.tsx"],
    appRefs: ["/chapter/:id"],
  },
  {
    slug: "chapter-notes",
    title: "Cross-device chapter notes",
    summary: "Notes are stored in chapter_notes table (RLS-scoped to the user), so they sync across web + iOS + Android. Auto-flush on chapter switch.",
    area: "Learning",
    status: "shipped",
    codeRefs: ["supabase/migrations/20260524000000_add_chapter_notes.sql"],
  },
  {
    slug: "qna-thread",
    title: "Q&A per chapter",
    summary: "Students can ask + answer questions on any chapter. Admin reply gets a badge. Upvote + thread comments.",
    area: "Learning",
    status: "shipped",
  },
  {
    slug: "certificates",
    title: "Course completion certificates",
    summary: "Auto-generated PDF certificates with student name, course title, completion date. Templates editable in /admin/certificates.",
    area: "Learning",
    status: "shipped",
    codeRefs: ["src/pages/admin/AdminCertificates.tsx", "src/pages/admin/AdminCertificateTemplateEditor.tsx"],
    appRefs: ["/admin/certificates"],
  },
  {
    slug: "course-reviews",
    title: "Course reviews",
    summary: "5-star + free-text reviews per offering, visible on the public offering page. Moderated in /admin/courses/:id/reviews.",
    area: "Learning",
    status: "shipped",
  },

  /* ─────────── Cohort ─────────── */
  {
    slug: "cohort-dashboard",
    title: "Cohort dashboard",
    summary: "Per-student cohort home: current week, assignment, mentor feedback, next session, attendance status. Replaces a separate course view for live-cohort enrolments.",
    area: "Cohort",
    status: "shipped",
    shipped_at: "2026-05-26",
    codeRefs: ["src/pages/CohortDashboard.tsx"],
    appRefs: ["/cohort/:slug"],
  },
  {
    slug: "assignment-submission",
    title: "Assignment submission",
    summary: "Per-week assignment form with text body, file uploads (Supabase Storage), optional link, opt-in for peer review. Edits-allowed until mentor opens it.",
    area: "Cohort",
    status: "shipped",
    shipped_at: "2026-05-26",
    codeRefs: ["src/components/cohort/AssignmentSubmissionForm.tsx"],
  },
  {
    slug: "mentor-feedback",
    title: "Mentor feedback",
    summary: "Admins review submitted assignments in /admin/cohort-submissions. Write feedback, mark status (revised, approved). Student sees feedback in their dashboard.",
    area: "Cohort",
    status: "shipped",
    shipped_at: "2026-05-26",
    codeRefs: ["src/pages/admin/AdminCohortSubmissions.tsx", "src/components/cohort/AssignmentFeedbackView.tsx"],
  },
  {
    slug: "peer-review",
    title: "Peer review board",
    summary: "Cohort-mates' opted-in assignments shown in a feed. Drawer with critique textarea + 5-star rating + draft save. Reachable from both /cohort and /community.",
    area: "Cohort",
    status: "shipped",
    shipped_at: "2026-05-26",
    codeRefs: ["src/components/cohort/PeerReviewBoard.tsx"],
    appRefs: ["/cohort/:slug", "/community"],
  },
  {
    slug: "attendance-gating",
    title: "Attendance gating",
    summary: "Admin marks who attended each live session. Below-threshold attendance can gate certificate eligibility.",
    area: "Cohort",
    status: "shipped",
    shipped_at: "2026-05-26",
    codeRefs: ["src/pages/admin/AdminCohortAttendance.tsx"],
  },
  {
    slug: "cohort-reminders",
    title: "Cohort reminder pings (email + WhatsApp)",
    summary: "pg_cron fires every 15 min. Three windows: 24h-before-due (assignment), 1h-before-session, 24-48h-after-missed-assignment. Email via Brevo, WhatsApp via Interakt.",
    area: "Cohort",
    status: "shipped",
    shipped_at: "2026-05-26",
    codeRefs: ["supabase/functions/notify-cohort/index.ts", "supabase/migrations/20260526220000_cohort_notify_cron.sql"],
  },

  /* ─────────── Community ─────────── */
  {
    slug: "community-posts",
    title: "Community posts + comments + likes",
    summary: "Twitter-like feed at /community. Cohort-scoped posts (My Cohort) or app-wide (Everyone). Threaded comments, ❤️ likes, mute-thread.",
    area: "Community",
    status: "shipped",
    codeRefs: ["src/pages/CommunityPage.tsx"],
    appRefs: ["/community"],
  },
  {
    slug: "thread-mute",
    title: "Mute-thread (local)",
    summary: "Users can mute their own posts to stop notifications. Stored in localStorage.",
    area: "Community",
    status: "partial",
    details: "Currently localStorage-only, doesn't sync across devices. Future work: store in user_thread_mutes table.",
  },
  {
    slug: "announcements",
    title: "Admin announcements",
    summary: "Admins broadcast announcements visible in the community feed with an Admin badge. Pinned to the top.",
    area: "Community",
    status: "shipped",
    appRefs: ["/admin/announcements"],
  },

  /* ─────────── Admin ─────────── */
  {
    slug: "admin-dashboard",
    title: "Admin dashboard (overview)",
    summary: "Single-page summary: live KPIs (revenue, students, refunds), top offerings, recent activity. Drills down into per-section pages.",
    area: "Admin",
    status: "shipped",
    appRefs: ["/admin"],
  },
  {
    slug: "admin-offerings",
    title: "Offerings management",
    summary: "CRUD on offerings: slug, title, price, tier, status (draft/active/archived). The OfferingEditor handles all fields including hero media + pricing + bumps.",
    area: "Admin",
    status: "shipped",
    appRefs: ["/admin/offerings"],
  },
  {
    slug: "admin-courses",
    title: "Course curriculum editor",
    summary: "Per-offering chapter list editor. Drag-reorder, VdoCipher upload, auto-pull duration + thumbnail from VdoCipher API.",
    area: "Admin",
    status: "shipped",
    appRefs: ["/admin/courses/:id/curriculum"],
  },
  {
    slug: "admin-users",
    title: "Users management + legacy badge",
    summary: "All users (new + legacy from TagMango) in one table. Filters: All / Active / Legacy + program vertical. Columns: name, email, phone, role, city, vertical, lifetime revenue.",
    area: "Admin",
    status: "shipped",
    shipped_at: "2026-05-26",
    appRefs: ["/admin/users"],
  },
  {
    slug: "admin-revenue",
    title: "Revenue page w/ date presets",
    summary: "Date filters: Today / Yesterday / 7d / 30d / 90d / All / Custom. Per-offering revenue, top buyers in window, CSV export, refund issuance.",
    area: "Admin",
    status: "shipped",
    shipped_at: "2026-05-26",
    appRefs: ["/admin/revenue"],
  },
  {
    slug: "admin-enrolments",
    title: "Enrolment management",
    summary: "Grant or revoke access to any offering for any user. Surfaces both purchase-derived and admin-granted enrolments.",
    area: "Admin",
    status: "shipped",
    appRefs: ["/admin/enrolments"],
  },
  {
    slug: "admin-cohorts",
    title: "Cohort weeks + sessions editor",
    summary: "Per-offering admin to define the week-by-week curriculum, assignments, due dates, and live session calendar.",
    area: "Admin",
    status: "shipped",
    appRefs: ["/admin/cohorts", "/admin/offerings/:id/cohort-weeks"],
  },
  {
    slug: "admin-applications",
    title: "Cohort applications inbox",
    summary: "Form responses from prospective cohort students. Approve → triggers an outreach email + creates a CRM contact.",
    area: "Admin",
    status: "shipped",
    appRefs: ["/admin/applications"],
  },
  {
    slug: "admin-legacy-mappings",
    title: "Legacy program mapping inbox",
    summary: "TagMango CSV programs that haven't been mapped to an offering yet. Per program: Map (link to offering, retro-grant matching users) or Skip.",
    area: "Admin",
    status: "shipped",
    appRefs: ["/admin/legacy-mappings"],
  },
  {
    slug: "admin-api",
    title: "API + integrations console (this page!)",
    summary: "/admin/api: tabs for Keys, Install (CLI + MCP setup), Webhooks, Activity log, Surface browser.",
    area: "Admin",
    status: "shipped",
    shipped_at: "2026-05-26",
    appRefs: ["/admin/api"],
  },
  {
    slug: "admin-docs",
    title: "Documentation portal (this page!)",
    summary: "/admin/docs: tabs for Overview, Features, Flows, Tech, Schema, API, Changelog. Search per tab, screenshot mobile/desktop toggle, downloadable as markdown.",
    area: "Admin",
    status: "shipped",
    shipped_at: "2026-05-27",
    appRefs: ["/admin/docs"],
  },

  /* ─────────── Marketing ─────────── */
  {
    slug: "lead-capture",
    title: "Lead capture API",
    summary: "Idempotent crm_contacts insert via lead_capture() RPC. Ad landing pages + marketing site fire it directly. Same email/phone is updated, not duplicated.",
    area: "Marketing",
    status: "shipped",
    shipped_at: "2026-05-26",
    codeRefs: ["supabase/migrations/20260526240000_marketing_crm_surface.sql"],
  },
  {
    slug: "user-tags",
    title: "User tags",
    summary: "Per-user free-form tags + values. Segment for marketing. Indexed for fast lookup. Bulk-tag via API.",
    area: "Marketing",
    status: "shipped",
    shipped_at: "2026-05-26",
  },
  {
    slug: "user-notes",
    title: "User notes",
    summary: "Free-form internal notes per user. Created_by tracking. Used by sales / CS team.",
    area: "Marketing",
    status: "shipped",
    shipped_at: "2026-05-26",
  },
  {
    slug: "marketing-prefs",
    title: "Email + WhatsApp + SMS opt-in flags",
    summary: "Per-user opt-in tracking with consent_at + unsubscribed_at. UTM provenance stored. Honored by bulk send + cohort notify.",
    area: "Marketing",
    status: "shipped",
    shipped_at: "2026-05-26",
  },
  {
    slug: "email-templates",
    title: "Email templates",
    summary: "Brevo-backed transactional templates. Editable from /admin/email-templates. Variables like {{first_name}} are interpolated by queue-transactional-email.",
    area: "Marketing",
    status: "shipped",
    appRefs: ["/admin/email-templates"],
  },
  {
    slug: "email-campaigns",
    title: "Bulk email campaigns",
    summary: "Send a template to a filtered audience. Honors opt-out. Throttled to avoid Brevo rate limits.",
    area: "Marketing",
    status: "shipped",
    appRefs: ["/admin/email-campaigns"],
  },
  {
    slug: "whatsapp-broadcasts",
    title: "WhatsApp broadcasts (planned)",
    summary: "Bulk WhatsApp via Interakt with template-based opt-out support. Transactional WhatsApp (cohort reminders) is shipped; full broadcast UI is planned.",
    area: "Marketing",
    status: "partial",
    details: "Transactional WhatsApp is live via notify-cohort. UI for bulk audience-targeted broadcasts is not yet built.",
  },
  {
    slug: "webhooks",
    title: "Webhook subscriptions",
    summary: "Subscribe external systems (Zapier, Make, n8n, HubSpot) to events: user.created, enrolment.granted, crm_contact.created, crm_contact.converted. HMAC-signed.",
    area: "Marketing",
    status: "shipped",
    shipped_at: "2026-05-26",
    appRefs: ["/admin/api"],
  },

  /* ─────────── Analytics ─────────── */
  {
    slug: "analytics-clients",
    title: "Meta Pixel + GA4 + Clarity + Twitter Pixel",
    summary: "All four client-side platforms fire from src/lib/analytics.ts. Config in /admin/analytics-settings (per-env enable + ID).",
    area: "Analytics",
    status: "shipped",
    codeRefs: ["src/lib/analytics.ts"],
    appRefs: ["/admin/analytics-settings"],
  },
  {
    slug: "meta-capi",
    title: "Meta Conversions API (server-side dedup)",
    summary: "Server-side purchase events sent to Meta with event_id matching the browser pixel, so Meta deduplicates and each purchase counts once but is robust to ad-blockers.",
    area: "Analytics",
    status: "shipped",
  },
  {
    slug: "funnel-analytics",
    title: "Funnel analytics RPC",
    summary: "admin-api action analytics.funnel returns signups, orders_created, orders_captured, orders_failed, enrolments for a date window. Used by CRM dashboards.",
    area: "Analytics",
    status: "shipped",
  },
  {
    slug: "utm-breakdown",
    title: "UTM source/campaign breakdown",
    summary: "admin-api action analytics.utm_breakdown rolls up crm_contacts by utm_source × utm_campaign with leads + converted counts.",
    area: "Analytics",
    status: "shipped",
  },

  /* ─────────── Content ─────────── */
  {
    slug: "vdocipher-streaming",
    title: "VdoCipher DRM video streaming",
    summary: "All videos go through VdoCipher for FairPlay/Widevine/PlayReady DRM. OTP exchanged on the server; player loaded with playback policy.",
    area: "Content",
    status: "shipped",
    codeRefs: ["supabase/functions/get-vdocipher-otp/index.ts"],
  },
  {
    slug: "workshop-archive",
    title: "Workshop archive bucket (Supabase Storage)",
    summary: "Migrated TagMango chapters live in a public Supabase Storage bucket as a plain HLS/MP4 fallback for non-DRM workshop content. 350 chapters re-hosted.",
    area: "Content",
    status: "shipped",
  },
  {
    slug: "fairplay-recovery",
    title: "FairPlay re-export from TagMango (in flight)",
    summary: "34 FairPlay-blocked chapters cannot be downloaded by us; PDF inventory sent to TagMango Support requesting bulk plain-HLS re-export.",
    area: "Content",
    status: "partial",
    details: "PDF generated at ~/Downloads/LevelUp_TagMango_ReExport_Request_2026-05-26.pdf. Awaiting TagMango response. Includes the 3 ADP truncated-URL chapters as a secondary section.",
  },

  /* ─────────── Payment ─────────── */
  {
    slug: "razorpay-webhook",
    title: "Razorpay webhook → enrolment",
    summary: "Captures payment.captured + payment.failed + refund.processed. Idempotent on razorpay_payment_id. Auto-creates the enrolment.",
    area: "Payment",
    status: "shipped",
    codeRefs: ["supabase/functions/razorpay-webhook/index.ts"],
  },
  {
    slug: "invoice-pdf",
    title: "GST invoice PDF",
    summary: "Per-order invoice generated at capture time with our GST number, totals, customer details. Stored in Supabase Storage, link emailed to buyer.",
    area: "Payment",
    status: "shipped",
  },

  /* ─────────── Platform ─────────── */
  {
    slug: "ios-shell",
    title: "iOS app shell (Capacitor)",
    summary: "Capacitor WebView wrapper around the React app. Apple Reader Rule compliant: purchases stay on the web, in-app is read-only for paid content.",
    area: "Platform",
    status: "shipped",
  },
  {
    slug: "android-shell",
    title: "Android app shell (Capacitor) + Play Store listing",
    summary: "Same Capacitor wrapper for Android, Path B compliant. AAB builds, signed keystore. Listed on Play Console under com.tagmango.leveluplearning.",
    area: "Platform",
    status: "shipped",
  },
  {
    slug: "sentry-monitoring",
    title: "Sentry error monitoring",
    summary: "Frontend + edge-function errors flow to Sentry. Release tracking by git SHA.",
    area: "Platform",
    status: "shipped",
  },
  {
    slug: "uptime-monitoring",
    title: "Uptime monitoring",
    summary: "External pings to the app + Supabase to alert on outage.",
    area: "Platform",
    status: "shipped",
  },

  /* ─────────── API ─────────── */
  {
    slug: "admin-api-surface",
    title: "Admin API edge function (74 actions)",
    summary: "Single endpoint /functions/v1/admin-api dispatches on body.action. Read/write/admin scope gates. Audit logged.",
    area: "API",
    status: "shipped",
    shipped_at: "2026-05-26",
    codeRefs: ["supabase/functions/admin-api/index.ts"],
  },
  {
    slug: "levelup-cli",
    title: "levelup CLI",
    summary: "Node CLI (no deps, ≥18) that wraps the admin API. Auth set, table rendering, --json flag, raw <action> escape hatch.",
    area: "API",
    status: "shipped",
    shipped_at: "2026-05-26",
    codeRefs: ["~/Claude/levelup-cli"],
  },
  {
    slug: "levelup-mcp",
    title: "levelup MCP server",
    summary: "JSON-RPC 2.0 over stdio. 74 tools auto-generated from list_actions. Drop into Claude Desktop / Claude Code / Cursor.",
    area: "API",
    status: "shipped",
    shipped_at: "2026-05-26",
    codeRefs: ["~/Claude/levelup-mcp"],
  },
  {
    slug: "api-key-management",
    title: "API key management UI",
    summary: "Issue + revoke keys with read/write/admin scope. Plaintext shown once at creation. Per-key install instructions dialog.",
    area: "API",
    status: "shipped",
    shipped_at: "2026-05-26",
    appRefs: ["/admin/api"],
  },
];
